### PR TITLE
UI update for draw activity

### PR DESCRIPTION
**Pull request by AbelianKraun**
This PR:

- Improve the UI of the drawing activity with material 3 standard.
- Reorganize the layout of the draw activity to improve the UX
- Add two fingers gesture for dragging and zooming

### CODE REVIEW

**Comment by jordenyt** [comment]
There is problem in the landscape view as you see in this screenshot:

image

The area for painting and sketching is too small and therefore I cannot do the inpainting on the picture.  This is why I set this activity to full screen and use "floating button" as toolbar cannot be put as "vertical".  Please check if you have any ideas to solve this problem and I know there should be some third party floating vertical toolbar to do this.  FYI, most of my SD work is done on Samsung tablet with stylus pen.  Therefore, I use landscape mode most of the time.

For the portrait mode, I am happy with it.

**Comment by jordenyt** [comment]
There is problem in the landscape view as you see in this screenshot:

image

The area for painting and sketching is too small and therefore I cannot do the inpainting on the picture.  This is why I set this activity to full screen and use "floating button" as toolbar cannot be put as "vertical".  Please check if you have any ideas to solve this problem and I know there should be some third party floating vertical toolbar to do this.  FYI, most of my SD work is done on Samsung tablet with stylus pen.  Therefore, I use landscape mode in most of the time.

**Comment by AbelianKraun** [comment]
I think the toolbar should stay, but the footer button should be vertical on the left or right as they take to much space. Like some other paint tools.

Let me try some other ideas.

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jordenyt** [comment]
I was trying to make the drawing area "expandable" by pinching gestures, but still failed to do so.  If we can do so, I think it worth scarify some space to the toolbar.  If not, then the top toolbar is occupying too much space, and I prefer not to keep it or change it to vertical.

**Comment by AbelianKraun** [comment]
I have already done gestures on canvas in a web environment, I will try to do it also on android and let you know.

Da: Jorden Tse ***@***.***>
Inviato: venerdì 21 luglio 2023 08:19
A: jordenyt/stable_diffusion_sketch ***@***.***>
Cc: Mauro Valvano ***@***.***>; Author ***@***.***>
Oggetto: Re: [jordenyt/stable_diffusion_sketch] UI update for draw activity (PR #5)


I was trying to make the drawing area "expandable" by pinching gestures, but still failed to do so. If we can do so, I think it worth scarify some space to the toolbar. If not, then the top toolbar is occupying too much space, and I prefer not to keep it or change it to vertical.

-

**Comment by AbelianKraun** [comment]
Updated the PR with pinch to zoom, two fingers draw, improved UI.

**Comment by jordenyt** [comment]
The pinch to zoom and two finger translate gestures has broken the functionality of:
1. Redo/Undo - cannot undo paint that do before zoom
2. Eraser and paint - cannot erase paint that do before zoom / translate

Besides, may I request to make the SeekBar in landscape view to be vertical?

**Comment by jordenyt** [comment]
For the fix,  I suggest introducing a "button" to on/off the "zooming/translate".  I found that it may be confusing to the program whether it is pinching event or a touch event as two fingers are not touched at the same time.  
For doing the translate, I suggest using "single finger touch" instead of two fingers, as I have a use case that the app is run under android emulator on PC which use mouse as input.

**Comment by AbelianKraun** [comment]
Yes, it can be an easy workaround to prevent accidental drawings or this type of issues.

**Comment by AbelianKraun** [comment]
Added switch draw / move view button

**Comment by jordenyt** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jsoft.diffusionpaint/com.jsoft.diffusionpaint.DrawingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.button.MaterialButton.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.button.MaterialButton.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
at com.jsoft.diffusionpaint.DrawingActivity.initButtons(DrawingActivity.java:261)
at com.jsoft.diffusionpaint.DrawingActivity.onCreate(DrawingActivity.java:149)
at android.app.Activity.performCreate(Activity.java:8305)
at android.app.Activity.performCreate(Activity.java:8284)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)

**Comment by AbelianKraun** [comment]
Fixed

**Comment by jordenyt** [comment]
I was trying to remove setScreenRotation() in DrawingActivity in your branch.  But the "paint" disappears / reloads when I change orientation.  Do you have any idea to resolve this? This is caused by onCreate() is being called when change screen orientation.

**Comment by AbelianKraun** [comment]
What you mean exactly with "disappear"? Can you show me a video?

**Comment by jordenyt** [comment]
Technically, it is not a bug for this PR.  But see if you have time to solve it.  

After I delete the function setScreenRotation() and onConfigurationChanged()..... I encountered drawing being reset after rotate screen:
[Screen_recording_20230803_113121.webm](https://github.com/jordenyt/stable_diffusion_sketch/assets/5007252/2c305e4c-d13b-44b4-b669-306c63d41bb5)

**Pull request closed without merging**
