### PR TITLE
Initial Material 3 Update

### PR DESCRIPTION
**Pull request by AbelianKraun**
I like the app but not the UI.

With this PR I have updated the themes to Material 3 and re-organized the main activity.

This would be the first step for other UI and UX improvements.

### CODE REVIEW

**Comment by jordenyt** [comment]
I think your UI/UX change is cool..... I don't have a good insight on UI/UX....

I have merged your pull request.  But also add an commit to hide the "create buttons" when a project/group/folder is selected.

**Comment by AbelianKraun** [comment]
Thank you

I have other ideas for the startup part, but I would like to first improve the drawing and view activity first if you agreed.

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jordenyt** [comment]
Just found an UI/UX problem in MainActivity. If start the app in landscape mode, cannot scroll to see "My images".  See if you have idea on how to resolve it.

**Comment by jordenyt** [comment]
If you are rewriting the MainActivity UI, I would like to add another button that can start drawing from selecting an image in the phone sdcard.  I have no place to put this new button previously.

**Pull request merged**
